version: "3"

services:
  speedtest:
    build: .
    image: adolfintel/speedtest:${TAG:-latest}
    ports:
      - "8888:80"
    volumes:
      - .:/var/www/html
  sqlsrv:
    build:
    image: microsoft/mssql-server-linux
    ports:
      - "1433:1433"
    environment:
      - HOMEBREW_NO_ENV_FILTERING=1
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password