version: "3"

services:
  speedtest:
    build: .
    image: navair/speedtest:${TAG:-latest}
    ports:
      - 8888:80
    volumes:
      - .:/var/www/html
    depends_on:
      - sqlsrv
  sqlsrv:
    image: microsoft/mssql-server-linux
    ports:
      - 1433:1433
    environment:
      - HOMEBREW_NO_ENV_FILTERING=1
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
